language: go
go:
  - 1.2
  - 1.3
  - 1.4
# Go 1.5beta1 has a bug on internal packages imports
# see https://github.com/golang/protobuf/issues/47#issuecomment-121528093
# - 1.5
  - tip
script:
  - go test ./...
notifications:
  email: false
sudo: false
